### ISSUE TITLE
Tabelle Day: workingTimeDifference und pauseTime entweder default setzen oder not nullable schalten

### ISSUE THREAD

**Issue by valientes** [Stier-09/hwr_zeiterfassung#80]
So geben die Funktionen getWorkingTimeAverageByDateBetweenAndHuman_Email und getPauseAverageByDateBetweenAndHuman_Email leere Optionals zurück, wenn das Datum existiert, aber workingTimeDifference bzw. pauseTime nicht explizit gesetzt wurden

**Comment by valientes** [comment]
Überlegung: workingTimeDifference: default -targetWorkingTime, pause: default 0

**Comment by NicoSteinmueller** [comment]
deshalb sind es Optionals
