### ISSUE TITLE
Zeiten dürfen sich nicht überlappen

### ISSUE THREAD

**Issue by valientes** [Stier-09/hwr_zeiterfassung#86]
Wenn sich Zeiten überlappen, kommt ein negatives Ergebnis bei `timeController.calculateTimeBetweenEntriesInMinutes` raus. Das sollte man verhindern

**Comment by NicoSteinmueller** [comment]
Zeiten können sich praktisch nicht überlappen, da immer die aktuelle Zeit vom Server genommen wird, bei der Korrektur wird es gefixt
