### ISSUE TITLE
mehr als 24 Stunden Arbeitszeit an einem Tag?

### ISSUE THREAD

**Issue by valientes** [Stier-09/hwr_zeiterfassung#89]
Wollen wir zulassen, dass ein Tag mehr Arbeitszeit als 24 Stunden enthalten kann? Wenn nein, muss das raus

**Comment by nicoregenberg** [comment]
nein, ist ja auch nicht möglich.

**Comment by NicoSteinmueller** [comment]
ist nicht möglich, da sich die Zeiten nicht überschneiden können und für jeden Tag nur Einträge des Tages erfasst werden
