### ISSUE TITLE
BookController.addTimeEntry Vortagsregelung

### ISSUE THREAD

**Issue by valientes** [Stier-09/hwr_zeiterfassung#92]
Warum schauen wir in den Tag davor, wenn am aktuellen Tag schon eine Zeit existiert? Können wir damit nicht Überschneidungen von Zeiten herbeiführen und wenn doch, wollen wir die wirklich haben?

**Comment by NicoSteinmueller** [comment]
Wird im BookController dadurch behandelt
```
  var time = getLastTimeFromDay(datetime.toLocalDate(), email, pause);

        if (time.isPresent() && time.get().getEnd() == null) 
```
